name: Detect_Changed_Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "changed=$CHANGED_FILES" >> "$GITHUB_OUTPUT"
