name: Detect Changed Files

on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.get_changes.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 2
      - name: Get changed files
        id: get_changes
        run: |
          CHANGED_FILES="$(git diff --name-only HEAD~1 HEAD)"
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "changed=$CHANGED_FILES" >> "$GITHUB_OUTPUT"
      - name: Save changed files to a file
        run: |
            echo "${{ steps.get_changes.outputs.changed }}" > changed_files.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: changed-files
           path: changed_files.txt

