name: Run After Detect

on:
  workflow_run:
    workflows: ["Detect Changed Files"]
    types:
      - completed

jobs:
  read-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: changed-files

      - name: Show changed files
        run: |
          echo "Changed files from previous workflow:"
          cat changed_files.txt
